#!/bin/bash

# ==============================================================================
# PETZEUSTECH UNLIMITED NETWORKS - "ZERO-CONFIG" DEPLOYMENT TOOL v3.0
# ==============================================================================

set -e

# Colors for the Elite Terminal UI
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

clear
echo -e "${BLUE}==================================================================${NC}"
echo -e "${BLUE}        PETZEUSTECH UNLIMITED - PRODUCTION DEPLOYMENT             ${NC}"
echo -e "${BLUE}        NO EXTERNAL SECRETS REQUIRED (POSTFIX + LOCAL DB)         ${NC}"
echo -e "${BLUE}==================================================================${NC}"

# Interactive Inputs
read -p "Target Domain (e.g., net.petzeustech.com): " DOMAIN
read -p "MySQL Database Name: " DB_NAME
read -p "MySQL Database User: " DB_USER
read -s -p "MySQL Database Password: " DB_PASS
echo -e "\n"
read -p "Admin Email (For MoMo Notifications): " ADMIN_EMAIL

if [ -z "$DOMAIN" ] || [ -z "$DB_NAME" ] || [ -z "$DB_USER" ] || [ -z "$DB_PASS" ] || [ -z "$ADMIN_EMAIL" ]; then
    echo -e "${RED}Error: All parameters required for node synchronization.${NC}"
    exit 1
fi

echo -e "${YELLOW}Synchronizing Core Repositories...${NC}"
apt update && apt upgrade -y

echo -e "${YELLOW}Deploying Nginx, MariaDB, PHP 8.1, and Postfix (Mail Relay)...${NC}"
apt install software-properties-common -y
add-apt-repository ppa:ondrej/php -y
apt update
# Non-interactive Postfix installation (local only)
echo "postfix postfix/main_mailer_type string 'Internet Site'" | debconf-set-selections
echo "postfix postfix/mailname string $DOMAIN" | debconf-set-selections
DEBIAN_FRONTEND=noninteractive apt install nginx mariadb-server mariadb-client php8.1-fpm php8.1-mysql php8.1-curl php8.1-gd php8.1-mbstring php8.1-xml php8.1-zip php8.1-bcmath unzip postfix -y

echo -e "${YELLOW}Securing Database & Initializing Tables...${NC}"
mysql -e "CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\`;"
mysql -e "CREATE USER IF NOT EXISTS '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASS}';"
mysql -e "GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'localhost';"
mysql -e "FLUSH PRIVILEGES;"

echo -e "${YELLOW}Deploying Silent phpMyAdmin Node...${NC}"
echo "phpmyadmin phpmyadmin/dbconfig-install boolean true" | debconf-set-selections
echo "phpmyadmin phpmyadmin/app-password-confirm password $DB_PASS" | debconf-set-selections
echo "phpmyadmin phpmyadmin/mysql/admin-pass password $DB_PASS" | debconf-set-selections
echo "phpmyadmin phpmyadmin/mysql/app-pass password $DB_PASS" | debconf-set-selections
echo "phpmyadmin phpmyadmin/reconfigure-webserver multiselect none" | debconf-set-selections
apt install phpmyadmin -y
ln -sf /usr/share/phpmyadmin /var/www/html/phpmyadmin

echo -e "${YELLOW}Generating Encrypted config.php Node...${NC}"
mkdir -p /var/www/html/backend
cat <<EOF > /var/www/html/backend/config.php
<?php
// AUTO-GENERATED BY PETZEUSTECH SETUP
session_start();
\$dbhost = 'localhost';
\$dbuser = '$DB_USER';
\$dbpass = '$DB_PASS';
\$dbname = '$DB_NAME';
\$admin_email = '$ADMIN_EMAIL';

\$conn = mysqli_connect(\$dbhost, \$dbuser, \$dbpass, \$dbname);
if (!\$conn) { die("Node Failure: Database unreachable."); }
define('CYCLE_DAYS', 4);
?>
EOF

echo -e "${YELLOW}Finalizing Nginx Protocol & SSL...${NC}"
cat <<EOF > /etc/nginx/sites-available/petzeustech
server {
    listen 80;
    server_name $DOMAIN;
    root /var/www/html;
    index index.html index.php;
    
    location / {
        try_files \$uri \$uri/ /index.html;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;
    }
}
EOF
ln -sf /etc/nginx/sites-available/petzeustech /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default
nginx -t && systemctl restart nginx

# SSL Auto-config
apt install certbot python3-certbot-nginx -y
certbot --nginx -d $DOMAIN --non-interactive --agree-tos --register-unsafely-without-email || true

# Permissions
chown -R www-data:www-data /var/www/html
chmod -R 755 /var/www/html
mkdir -p /var/www/html/uploads
chmod -R 775 /var/www/html/uploads

echo -e "${BLUE}==================================================================${NC}"
echo -e "${GREEN}        DEPLOYMENT COMPLETE - NO EXTERNAL SECRETS NEEDED          ${NC}"
echo -e "${BLUE}==================================================================${NC}"
echo -e "${CYAN}Public Portal:${NC}   https://$DOMAIN"
echo -e "${CYAN}DB Admin Panel:${NC}  https://$DOMAIN/phpmyadmin"
echo -e "${CYAN}Email Alerts:${NC}    Routing to $ADMIN_EMAIL"
echo -e "${BLUE}==================================================================${NC}"
